### ISSUE TITLE
how can i use  'debounceTime' on EasySearchBar

### ISSUE THREAD

**Issue by bluesiboy** [4inka/flutter_easy_search_bar#11]
when type search words, OnSearch will run many times.

**Comment by bluesiboy** [comment]
or listen Enter keyboard event.

**Comment by eunicevassoa** [comment]
Hello @bluesiboy,

First of all, I'm sorry for only being able to respond to your issue after a long time.
There's a parameter called `debounceDuration` and I think it can help you achieve what you need.

Have a nice day
