### ISSUE TITLE
Clear text icon button on the right

### ISSUE THREAD

**Issue by jrcacd** [4inka/flutter_easy_search_bar#13]

**Comment by eunicevassoa** [comment]
Hello @jrcacd ,

First of all, I'm sorry for only being able to respond to your issue after a long time.
I'm currently working on it and will update the package ASAP.

Have a nice day

**Comment by eunicevassoa** [comment]
Hello once again @jrcacd,

There's finally a new version of the package that that a parameter called `showClearSearchIcon` that will add the clear button if set to true

**Comment by jrcacd** [comment]
Thanks
