### ISSUE TITLE
Not load EasySearchBar

### ISSUE THREAD

**Issue by felipeparente** [4inka/flutter_easy_search_bar#2]
Não carrega a classe "EasySearchBar".
Importei o "easy_search_bar: ^2.1.1" no pubspec, mas na classe principal não dá opção de carregar a Classe.
Mesmo adicionando "import 'package:easy_search_bar/easy_search_bar.dart';" ocorre erro.

**Comment by eunicevassoa** [comment]
Oi @felipeparente 

Não sei se é o seu caso, mas ultimamente eu tenho tido problemas ao instalar dependências no projecto dentro do VS Code quando faz o import automático depois de salvar o ficheiro pubspec.yaml. Eu geralmente tenho que correr o `flutter pub get` via consola para ele importar as últimas dependências.
Por favor, tente correr o comando na consola e ver se dá algum resultado.

**Comment by felipeparente** [comment]
No meu caso, creio que não seja isso, pois outras bibliotecas instalam normalmente, e eu instalei a sua LIB pelo comando " $ flutter pub add flutter_search_bar"

Acabei tendo que utilizar outra lib, mesmo assim, deixei a mensagem para vc ficar ciente.

**Comment by felipeparente** [comment]
No meu caso, creio que não seja isso, pois outras bibliotecas instalam normalmente, e eu instalei a sua LIB pelo comando " $ flutter pub add easy_search_bar"

Acabei tendo que utilizar outra lib, mesmo assim, deixei a mensagem para vc ficar ciente.

**Comment by eunicevassoa** [comment]
Obrigada pelo alerta.
