### ISSUE TITLE
Deprecated titleTextStyle theme

### ISSUE THREAD

**Issue by esaiaswestberg** [4inka/flutter_easy_search_bar#27]
## The Issue

In a recent update of the Flutter framework, older TextTheme styles, such as _headline6_, became deprecated and are replaced by new names for the styles.

When trying to build a flutter project which uses _easy_search_bar_ one now encounters the following error message:
```
easy_search_bar-2.5.0/lib/easy_search_bar.dart:377:25: Error: The getter 'headline6' isn't defined for the class 'TextTheme'.
 - 'TextTheme' is from 'package:flutter/src/material/text_theme.dart' ('/usr/bin/flutter/packages/flutter/lib/src/material/text_theme.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'headline6'.
        theme.textTheme.headline6!.copyWith(color: foregroundColor);
                        ^^^^^^^^^
../../../../.pub-cache/hosted/pub.dev/easy_search_bar-2.5.0/lib/easy_search_bar.dart:491:60: Error: The argument type 'TextStyle?' can't be assigned to the parameter type 'TextStyle' because 'TextStyle?' is nullable and 'TextStyle' isn't.
 - 'TextStyle' is from 'package:flutter/src/painting/text_style.dart' ('/usr/bin/flutter/packages/flutter/lib/src/painting/text_style.dart').
                                                    style: titleTextStyle,
                                                           ^
```

This indicated that the default titleTextStyle does not work as it is null as of the new version of the framework.

## Proposed solution

Using one of the new [TextTheme styles](https://api.flutter.dev/flutter/material/TextTheme-class.html). My proposal would be to use _titleLarge_ as it matches the old _headline6_.

|Property|headline6 _(old)_|titleLarge _(new)_|
|------|------|------|
|Size|20|20|
|Weight|Medium|Medium|
|Spacing|0.15|0.15|

As you can see, they are identical and therefor it will not cause any issues for any future users or any existing users.

**Comment by esaiaswestberg** [comment]
Source for old theme values: https://web.archive.org/web/20210625133010/https://api.flutter.dev/flutter/material/TextTheme-class.html

**Comment by wantroba** [comment]
When will this change go live? I am unable to use the lib because of this error.
