### ISSUE TITLE
Missing systemOverlayStyle

### ISSUE THREAD

**Issue by troncomputers** [4inka/flutter_easy_search_bar#3]
I need to be able to set `systemOverlayStyle`, just like normal `AppBar` has.

**Comment by eunicevassoa** [comment]
Hi @troncomputers 

I just added the parameter and it should work properly. Please upgrade the package version to 2.3.0 and search for `systemOverlayStyle` and try to set custom values as you wish.

Have a nice day.

**Comment by troncomputers** [comment]
Wow that was quick 💪🤘

There is something else, maybe I did it wrong. The `statusBarColor: Colors.transparent` is not applied.

```dart
SystemUiOverlayStyle getStatusBarTheme() {
  return SystemUiOverlayStyle(
    statusBarColor: Colors.transparent,
    systemNavigationBarColor: Get.isDarkMode ? darkTheme.scaffoldBackgroundColor : lightTheme.scaffoldBackgroundColor,
    statusBarBrightness: Brightness.light,
    statusBarIconBrightness: Brightness.light,
  );
}
```

![appbar_search](https://user-images.githubusercontent.com/29543667/149612215-5f4ee940-7204-4e76-b506-7e70a4381990.png)

**Comment by eunicevassoa** [comment]
Hello once again @troncomputers 

There was an actual issue with that, but it should be fixed now.
You can update to version 2.3.1 and try again.

**Comment by troncomputers** [comment]
Perfect ✌ thank you.
