### ISSUE TITLE
using the native appbar look

### ISSUE THREAD

**Issue by 0xpr03** [4inka/flutter_easy_search_bar#7]
The native appbar uses a white color for text and icons for my theme.
Now if I use the EasySearchBar, I can't get this to work in a way that I don't a) hardcode the color and b) the back-button of the search doesn't get the wrong color:
```dart
EasySearchBar(
          title: Text(_excercise.name),
          foregroundColor: Colors.white, // fixes at least the normal title, but not the back button in search
          searchHintText: 'attribute name...',
          onSearch: (value) => setState(() => searchText = value),
        ),
```
![grafik](https://user-images.githubusercontent.com/1280209/192816802-ea5ae051-8f00-45fe-841e-8e742e5db975.png)
![grafik](https://user-images.githubusercontent.com/1280209/192816863-d109f668-b84e-4cc5-aef6-e3edfdc00ef8.png)

**Comment by eunicevassoa** [comment]
Hello @0xpr03 

I have published a new package version and worked on this. Please check again to see if it's ok.

Have a nice day

**Comment by 0xpr03** [comment]
Hey thanks for fixing this, didn't have a time to test this out until now.
